site_name: PlexPipe
site_url: https://stallaertlab.github.io/plex_pipe/
repo_url: https://github.com/StallaertLab/plex-pipe
repo_name: StallaertLab/plex-pipe
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

hooks:
  - docs/hooks.py

extra:
  version:
    provider: mike
extra_css:
  - stylesheets/extra.css

nav:
  - What is PlexPipe?: what_is_plexpipe.md
  - Analysis Steps:
    - Overview: analysis_steps/00_steps_overview.md
    - 01_ROI Definition: analysis_steps/01_roi_definition.md
    - 02_ROI Cutting: analysis_steps/02_roi_cutting.md
    - 03_Quality_Control: analysis_steps/03_quality_control.md
    - 04_Image_Processing: analysis_steps/04_image_processing.md
    - 05_Quantification: analysis_steps/05_quantification.md
  - Configuration:
      - Overview: configuration/config_overview.md
      - Reference: configuration/reference.md
      - Channel Selection: configuration/channel-selection.md
  - How To Use:
    - Installation: usage/installation.md
    - Execution Modes: usage/execution_modes.md
    - Input Data: usage/input_data.md
    - Globus Integration: usage/globus.md
    - Processors: usage/processors.md
  - API Reference: api.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_root_toc_entry: false
            merge_init_into_class: true
            show_source: false
            extra:
              show_symbol_type: true

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details  # Optional: allows for collapsible notes
  - pymdownx.superfences # Optional: allows nesting code blocks in notes
  - md_in_html
