# Configuration for different workstations
workstations:

  WORKSTATION_NAME_1: # host name of the workstation (what platform.node() returns)
    model_path: "" # path to the SAM2 model
    sam2_env: "" # path to the SAM2 environment

  DESKTOP-S71S74E:
    model_path: "/mnt/d/sam2_test/sam2"
    sam_env: "/home/kasia/miniforge3/envs/sam2-env/bin/python"
